package com.tectoro.Exception;

class Demo1
{
	public void  fun() {
	try
	{
	
		int a=10,b=0,c;
		c=a/b;
}
	catch(Exception e)
	{
		System.out.println(" some error occured ");
	}
	}
}
